[package]
name = "scguild"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "scguild"
path = "src/lib.rs"

[[bin]]
name = "scguild"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.68"
poise = "0.5.2"
tracing = "0.1.37"
tokio = "1.26.0"
tracing-bunyan-formatter = "0.3.9"
tracing-subscriber = "0.3.17"
