[package]
name = "scguild"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "scguild"
path = "src/lib.rs"

[[bin]]
name = "scguild"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.68"
poise = "0.5.2"
shuttle-poise = "0.30.0"
shuttle-runtime = "0.30.0"
shuttle-secrets = "0.30.0"
tracing = "0.1.37"
tokio = "1.26.0"
