# fly.toml app configuration file generated for dscguild on 2023-04-26T22:58:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dscguild"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  auto_rollback = true

[env]
  # Application specific variables
  APP_APPLICATION__BASE_URL = "https://dscguild.fly.dev"

  ## Newsletter module variables
  APP_NEWSLETTER_DATABASE__DATABASE_NAME = "newsletter"
  APP_NEWSLETTER_DATABASE__HOST = "damccull-postgres.flycast"
  APP_NEWSLETTER_DATABASE__PASSWORD = "Do not put password here. Put it in a 'fly secret'."
  APP_NEWSLETTER_DATABASE__PORT = "5432"
  APP_NEWSLETTER_DATABASE__REQUIRE_SSL = "false"
  APP_NEWSLETTER_DATABASE__USERNAME = "newsletter"

  ## Star Citizen API module variables
  APP_SCAPI_DATABASE__DATABASE_NAME = "scapi"
  APP_SCAPI_DATABASE__HOST = "damccull-postgres.flycast"
  APP_SCAPI_DATABASE__PASSWORD = "Do not put password here. Put it in a 'fly secret'."
  APP_SCAPI_DATABASE__PORT = "5432"
  APP_SCAPI_DATABASE__REQUIRE_SSL = "false"
  APP_SCAPI_DATABASE__USERNAME = "scapi"
  APP_EMAIL_CLIENT__SENDER_EMAIL = "scguild@digitalmccullough.com"

  # Fly.io variables
  PRIMARY_REGION = "lax"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/health_check"
    protocol = "http"
