name: Docker Package Build and Push

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to registries
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/damccull/scguild-rs/scguild-rs:latest
          push: ${{ github.ref == 'refs/heads/main' }}
        
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Get the version
#         id: vars
#         run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
#       - name: Build the tagged Docker image
#         run: docker build . --file Dockerfile --tag damccull/scguild:${{steps.vars.outputs.tag}}
#       - name: Push the tagged Docker image
#         run: docker push damccull/scguild:${{steps.vars.outputs.tag}}
#       - name: Set the 'latest' Docker image
#         run: docker tag damccull/scguild:${{steps.vars.outputs.tag}} damccull/scguild:latest
#       - name: Push the 'latest' tag
#         run: docker push damccull/scguild:latest
